// Payload CMS import map — auto-generated by payload, do not edit manually
import { default as PartnerDashboard_view } from '../../payload/views/PartnerDashboard'
import { default as MembersView_view } from '../../payload/views/MembersView'
import { default as EnrollmentsView_view } from '../../payload/views/EnrollmentsView'
import { default as BillsView_view } from '../../payload/views/BillsView'
import { default as SchedulesView_view } from '../../payload/views/SchedulesView'
import { default as ProfileView_view } from '../../payload/views/ProfileView'

export const importMap = {
  "/src/payload/views/PartnerDashboard#default": PartnerDashboard_view,
  "/src/payload/views/MembersView#default": MembersView_view,
  "/src/payload/views/EnrollmentsView#default": EnrollmentsView_view,
  "/src/payload/views/BillsView#default": BillsView_view,
  "/src/payload/views/SchedulesView#default": SchedulesView_view,
  "/src/payload/views/ProfileView#default": ProfileView_view,
}
