"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dFHXetYIhdY
 */

import { FormEvent, useState, useEffect, useLayoutEffect } from "react";
import { signIn, useSession } from "next-auth/react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import Link from "next/link";
import { useRouter } from "next/navigation";
interface UserAuthFormProps extends React.HTMLAttributes<HTMLDivElement> {}
import { toast } from "sonner";
import avatarsData from "@/db/avatars.json";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import Image from "next/image";

export function AccountOnboarding({ callbackUrl }: any) {
  //   console.log(searchParams?.callbackUrl);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const { data: session } = useSession();
  const [email, setEmail] = useState(session?.user?.email || "");
  const [password, setPassword] = useState("");
  const [userName, setUsername] = useState("");
  const [loadingVerify, setLoadingVerify] = useState(false);
  const [userAvatar, setAvatar] = useState("/image/avatar/Milo.svg");
  const router = useRouter();

  useLayoutEffect(() => {
    setLoadingVerify(true);
    //@ts-ignore
    if (session?.user?.emailVerified === true) {
      router.push(callbackUrl || "/");
      setLoadingVerify(false);
    }
    //@ts-ignore
  }, [callbackUrl, router, session?.user?.emailVerified]);

  const onSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsLoading(true);
    // check if all data is inputted
    if (!email || !password || !userName || !userAvatar) {
      setIsLoading(false);
      return toast("All fields are required", {
        description: "all fields are required, please fill them out",
      });
    }
    console.log(email, password, userName, userAvatar);
    try {
      const response = await fetch("/api/auth/signup", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ email, password, userName, userAvatar }),
      });
      console.log(response);
      if (!response.ok) {
        toast(response?.statusText || "something went wrong", {
          description: "something went wrong, please try again later",
          action: {
            label: "Login",
            onClick: () => router.push("/login"),
          },
        });
      }
      //   return redirect("/auth/signin");
      setIsLoading(false);
      if (response.ok) {
        toast("Register Successful 🎉", {
          description: "Your account has been created successfully",
          action: {
            label: "Home",
            onClick: () => router.push("/"),
          },
        });
        return router.push(callbackUrl || "/");
      }
    } catch (error) {
      setIsLoading(false);
      toast("something went wrong", {
        description: "something went wrong, please try again later",
        action: {
          label: "Home",
          onClick: () => router.push("/"),
        },
      });
    }
  };
  const [avatars, setAvatars] = useState([]);

  useEffect(() => {
    // Set the avatars data when the component mounts
    setAvatars(avatarsData as any);
  }, []);
  return (
    <Card className="w-full max-w-3xl">
      <form onSubmit={onSubmit}>
        <CardHeader>
          <CardTitle className="text-center text-3xl">
            Account Setup Wizard
          </CardTitle>
          <Image
            src="/image/lordicons/face-id.gif"
            alt=""
            width={70}
            height={70}
            className="m-2 mx-auto border-spacing-2 rounded-lg border border-double border-primary dark:opacity-100 dark:contrast-100 dark:invert dark:filter"
          />
          <CardDescription>
            Let us setup your account quickly. You will also be able to sign in
            using these credentials as well as the provider you choose.
          </CardDescription>
        </CardHeader>
        {loadingVerify === true ? (
          "loading"
        ) : (
          <>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <Label htmlFor="username">Username</Label>
                  <Input
                    autoComplete="username"
                    autoCorrect="off"
                    disabled={isLoading}
                    required={true}
                    onChange={(e) => setUsername(e.target.value)}
                    id="username"
                    placeholder="Enter your username"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="password">Password</Label>
                  <Input
                    id="password"
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="password"
                    type="password"
                    autoCapitalize="none"
                    autoComplete="password"
                    autoCorrect="off"
                    disabled={isLoading}
                    required={true}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="image">Choose your image</Label>
                <Select required={false} onValueChange={(e) => setAvatar(e)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="avatar" />
                  </SelectTrigger>
                  <SelectContent className="h-60 overflow-y-auto ">
                    {avatars.map((avatar: any, index: any) => (
                      <SelectItem
                        key={avatar.name}
                        className=""
                        value={avatar.icon}
                      >
                        <div className="flex  flex-row items-center justify-between">
                          <Image
                            alt={avatar.name}
                            height={30}
                            width={30}
                            className="mr-2"
                            src={avatar.icon}
                            style={{
                              objectFit: "fill",
                            }}
                          />
                          <span>{avatar.name}</span>
                        </div>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto" disabled={isLoading}>
                {/* {isLoading && (
              <Icons.spinner className="mr-2 h-4 w-4 animate-spin" />
            )} */}
                Abrakadabra!
              </Button>
            </CardFooter>
          </>
        )}
      </form>
    </Card>
  );
}
