/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dFHXetYIhdY
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export function AccountOnboarding() {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <CardTitle className="text-2xl">Account Setup Wizard</CardTitle>
        <CardDescription>
          Choose an image to personalize your account
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="username">Username</Label>
            <Input id="username" placeholder="Enter your username" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              placeholder="Enter your password"
              type="password"
            />
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="image">Choose your image</Label>
          <Select>
            <option>Mountain</option>
            <option>Beach</option>
            <option>City</option>
            <option>Space</option>
            <option>Forest</option>
          </Select>
        </div>
      </CardContent>
      <CardFooter>
        <Button className="ml-auto">Next</Button>
      </CardFooter>
    </Card>
  );
}
