"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZyO5AHpqFL2
 */
import { Button } from "@/components/ui/button";
import avatarsData from "@/db/avatars.json";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

export function Avatarz() {
  const [avatars, setAvatars] = useState([]);

  useEffect(() => {
    // Set the avatars data when the component mounts
    setAvatars(avatarsData as any);
  }, []);
  return (
    <div className="grid grid-cols-1 gap-4 p-4 md:grid-cols-2 md:p-6 lg:grid-cols-3">
      {avatars.map((avatar: any, index: any) => (
        <div key={index}>
          <div className="group relative overflow-hidden rounded-lg border border-solid">
            <Link href={`/avatar/${avatar.name}/edit`}>
              <Button
                className="absolute right-2 top-2"
                size="md"
                variant="default"
              >
                Edit
              </Button>
            </Link>
            <Button
              className="absolute inset-0 z-10 flex items-center justify-center rounded-lg bg-gray-900/40 opacity-0 transition-opacity dark:bg-gray-50"
              size="md"
              variant="ghost"
            >
              <ZoomInIcon className="fill-accent h-6 w-6" />
              View zoom
              <span className="sr-only">View item</span>
            </Button>
            <Image
              alt="Product 1"
              className="h-60 w-full object-cover"
              height={300}
              width={400}
              src={avatar.icon}
              style={{
                objectFit: "fill",
              }}
            />
            <div className="flex flex-row items-center justify-between bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                {avatar.name}
              </h3>
              <p className="text-sm font-bold text-secondary dark:text-secondary">
                zoom
              </p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function ZoomInIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="11" x2="11" y1="8" y2="14" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </svg>
  );
}
