"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZyO5AHpqFL2
 */
import { Button } from "@/components/ui/button";
import avatarsData from "@/db/avatars.json";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";

export function Avatarz() {
  const [avatars, setAvatars] = useState([]);

  useEffect(() => {
    // Set the avatars data when the component mounts
    setAvatars(avatarsData as any);
  }, []);
  return (
    <div className="mt-16 grid grid-cols-1 gap-4 p-4 md:grid-cols-2 md:p-6 lg:mt-28 lg:grid-cols-3">
      {avatars.map((avatar: any, index: any) => (
        <div key={index}>
          <div className="group relative overflow-hidden rounded-lg border border-solid">
            <Link href={`/avatar/edit/${avatar.name}`}>
              <Button
                className="absolute right-2 top-2"
                size="md"
                variant="outline"
              >
                Edit
              </Button>
            </Link>
            <Image
              alt={avatar.name}
              className="h-60 w-full object-cover"
              height={300}
              width={400}
              src={avatar.icon}
              style={{
                objectFit: "fill",
              }}
            />
            <div className="flex flex-row items-center justify-between bg-white p-4 dark:bg-gray-950">
              <h3 className="text-lg font-semibold md:text-xl">
                {avatar.name}
              </h3>

              <Drawer>
                <DrawerTrigger>
                  <Button
                    variant="link"
                    className="text-sm font-bold text-secondary dark:text-secondary"
                  >
                    <ZoomInIcon />
                    <span>ZOOM</span>
                  </Button>
                </DrawerTrigger>
                <DrawerContent>
                  <DrawerHeader>
                    <DrawerTitle>{avatar.name}</DrawerTitle>
                    <DrawerDescription>
                      <Image
                        alt={avatar.name}
                        className="h-60 w-full object-cover"
                        height={500}
                        width={500}
                        src={avatar.icon}
                        style={{
                          objectFit: "fill",
                        }}
                      />
                    </DrawerDescription>
                  </DrawerHeader>
                  <DrawerFooter>
                    <Link href={`/avatar/edit/${avatar.name}`}>
                      <Button
                        className="absolute right-2 top-2"
                        size="md"
                        variant="outline"
                      >
                        Edit
                      </Button>
                    </Link>
                    <DrawerClose>
                      <Button variant="destructive">Close</Button>
                    </DrawerClose>
                  </DrawerFooter>
                </DrawerContent>
              </Drawer>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

function ZoomInIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <line x1="21" x2="16.65" y1="21" y2="16.65" />
      <line x1="11" x2="11" y1="8" y2="14" />
      <line x1="8" x2="14" y1="11" y2="11" />
    </svg>
  );
}
