/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VrXnya9ngDr
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import MaxWidthWrapper from "./maxWidthWrapper"

export function EnrollForm() {
  return (
    <MaxWidthWrapper>
      <Card className="w-full relative bottom-36">
        <CardHeader>
          <CardTitle>Karate Dojo new membership</CardTitle>
          <CardDescription>Fill out the form below to register as a new member.</CardDescription>
        </CardHeader>
        <CardContent>
          <form className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="full-name">Full Name</Label>
                <Input id="full-name" placeholder="Enter your full name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="father-name">Father Name</Label>
                <Input id="father-name" placeholder="Enter your father's name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="mother-name">Mother Name</Label>
                <Input id="mother-name" placeholder="Enter your mother's name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="address">Address</Label>
                <Textarea id="address" placeholder="Enter your address" />
              </div>
            </div>
            <div className="space-y-4">
              <div className="grid gap-2">
                <Label htmlFor="zip-code">Zip Code</Label>
                <Input id="zip-code" placeholder="Enter your zip code" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="phone">Phone Number</Label>
                <Input id="phone" type="tel" placeholder="Enter your phone number" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="Enter your email" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="dob">Date of Birth</Label>
                  <Input id="dob" type="date" />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="age">Age</Label>
                  <Input id="age" type="number" placeholder="Enter your age" />
                </div>
              </div>
            </div>
          </form>
        </CardContent>
        <CardFooter>
          <Button type="submit" className="ml-auto">
            Register
          </Button>
        </CardFooter>
      </Card>
    </MaxWidthWrapper>
  )
}
